// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: sentinel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Uid               string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CpuCoresRequested float64                `protobuf:"fixed64,4,opt,name=cpu_cores_requested,json=cpuCoresRequested,proto3" json:"cpu_cores_requested,omitempty"`
	MemoryGbRequested float64                `protobuf:"fixed64,5,opt,name=memory_gb_requested,json=memoryGbRequested,proto3" json:"memory_gb_requested,omitempty"`
	WorkloadType      string                 `protobuf:"bytes,6,opt,name=workload_type,json=workloadType,proto3" json:"workload_type,omitempty"` // e.g. BATCH, GPU_INFERENCE, LATENCY_CRITICAL
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PodSpec) Reset() {
	*x = PodSpec{}
	mi := &file_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpec) ProtoMessage() {}

func (x *PodSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpec.ProtoReflect.Descriptor instead.
func (*PodSpec) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *PodSpec) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PodSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodSpec) GetCpuCoresRequested() float64 {
	if x != nil {
		return x.CpuCoresRequested
	}
	return 0
}

func (x *PodSpec) GetMemoryGbRequested() float64 {
	if x != nil {
		return x.MemoryGbRequested
	}
	return 0
}

func (x *PodSpec) GetWorkloadType() string {
	if x != nil {
		return x.WorkloadType
	}
	return ""
}

type NodeCandidate struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Go-owned capacities (from K8s internal scheduler state snapshot)
	AllocatableCpu                float64 `protobuf:"fixed64,2,opt,name=allocatable_cpu,json=allocatableCpu,proto3" json:"allocatable_cpu,omitempty"`
	AllocatableMemoryGb           float64 `protobuf:"fixed64,3,opt,name=allocatable_memory_gb,json=allocatableMemoryGb,proto3" json:"allocatable_memory_gb,omitempty"`
	SchedulerExpectedFreeCpu      float64 `protobuf:"fixed64,4,opt,name=scheduler_expected_free_cpu,json=schedulerExpectedFreeCpu,proto3" json:"scheduler_expected_free_cpu,omitempty"`
	SchedulerExpectedFreeMemoryGb float64 `protobuf:"fixed64,5,opt,name=scheduler_expected_free_memory_gb,json=schedulerExpectedFreeMemoryGb,proto3" json:"scheduler_expected_free_memory_gb,omitempty"`
	// Node-reported telemetry (self-reported via node agent heartbeat)
	ReportedAllocatableCpu      float64 `protobuf:"fixed64,6,opt,name=reported_allocatable_cpu,json=reportedAllocatableCpu,proto3" json:"reported_allocatable_cpu,omitempty"`
	ReportedUsedCpu             float64 `protobuf:"fixed64,7,opt,name=reported_used_cpu,json=reportedUsedCpu,proto3" json:"reported_used_cpu,omitempty"`
	ReportedFreeCpu             float64 `protobuf:"fixed64,8,opt,name=reported_free_cpu,json=reportedFreeCpu,proto3" json:"reported_free_cpu,omitempty"`
	ReportedAllocatableMemoryGb float64 `protobuf:"fixed64,9,opt,name=reported_allocatable_memory_gb,json=reportedAllocatableMemoryGb,proto3" json:"reported_allocatable_memory_gb,omitempty"`
	ReportedUsedMemoryGb        float64 `protobuf:"fixed64,10,opt,name=reported_used_memory_gb,json=reportedUsedMemoryGb,proto3" json:"reported_used_memory_gb,omitempty"`
	ReportedFreeMemoryGb        float64 `protobuf:"fixed64,11,opt,name=reported_free_memory_gb,json=reportedFreeMemoryGb,proto3" json:"reported_free_memory_gb,omitempty"`
	// Telemetry timing tracking for freshness and CV consistency checks
	LastHeartbeatTimestamp   float64   `protobuf:"fixed64,12,opt,name=last_heartbeat_timestamp,json=lastHeartbeatTimestamp,proto3" json:"last_heartbeat_timestamp,omitempty"`              // Unix epoch in seconds
	RecentHeartbeatIntervals []float64 `protobuf:"fixed64,13,rep,packed,name=recent_heartbeat_intervals,json=recentHeartbeatIntervals,proto3" json:"recent_heartbeat_intervals,omitempty"` // History of durations in seconds
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *NodeCandidate) Reset() {
	*x = NodeCandidate{}
	mi := &file_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCandidate) ProtoMessage() {}

func (x *NodeCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCandidate.ProtoReflect.Descriptor instead.
func (*NodeCandidate) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCandidate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeCandidate) GetAllocatableCpu() float64 {
	if x != nil {
		return x.AllocatableCpu
	}
	return 0
}

func (x *NodeCandidate) GetAllocatableMemoryGb() float64 {
	if x != nil {
		return x.AllocatableMemoryGb
	}
	return 0
}

func (x *NodeCandidate) GetSchedulerExpectedFreeCpu() float64 {
	if x != nil {
		return x.SchedulerExpectedFreeCpu
	}
	return 0
}

func (x *NodeCandidate) GetSchedulerExpectedFreeMemoryGb() float64 {
	if x != nil {
		return x.SchedulerExpectedFreeMemoryGb
	}
	return 0
}

func (x *NodeCandidate) GetReportedAllocatableCpu() float64 {
	if x != nil {
		return x.ReportedAllocatableCpu
	}
	return 0
}

func (x *NodeCandidate) GetReportedUsedCpu() float64 {
	if x != nil {
		return x.ReportedUsedCpu
	}
	return 0
}

func (x *NodeCandidate) GetReportedFreeCpu() float64 {
	if x != nil {
		return x.ReportedFreeCpu
	}
	return 0
}

func (x *NodeCandidate) GetReportedAllocatableMemoryGb() float64 {
	if x != nil {
		return x.ReportedAllocatableMemoryGb
	}
	return 0
}

func (x *NodeCandidate) GetReportedUsedMemoryGb() float64 {
	if x != nil {
		return x.ReportedUsedMemoryGb
	}
	return 0
}

func (x *NodeCandidate) GetReportedFreeMemoryGb() float64 {
	if x != nil {
		return x.ReportedFreeMemoryGb
	}
	return 0
}

func (x *NodeCandidate) GetLastHeartbeatTimestamp() float64 {
	if x != nil {
		return x.LastHeartbeatTimestamp
	}
	return 0
}

func (x *NodeCandidate) GetRecentHeartbeatIntervals() []float64 {
	if x != nil {
		return x.RecentHeartbeatIntervals
	}
	return nil
}

type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           *PodSpec               `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Nodes         []*NodeCandidate       `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Gamma         float64                `protobuf:"fixed64,3,opt,name=gamma,proto3" json:"gamma,omitempty"` // Trust discount exponent (ablation parameter)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreRequest) GetPod() *PodSpec {
	if x != nil {
		return x.Pod
	}
	return nil
}

func (x *ScoreRequest) GetNodes() []*NodeCandidate {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ScoreRequest) GetGamma() float64 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

type NodeScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Eta           float64                `protobuf:"fixed64,2,opt,name=eta,proto3" json:"eta,omitempty"`                                 // Heuristic optimization score (from CostEngine)
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                   // Composite trust rating (kappa_i)
	FinalScore    float64                `protobuf:"fixed64,4,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"` // eta * (kappa_i ^ gamma)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeScore) Reset() {
	*x = NodeScore{}
	mi := &file_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScore) ProtoMessage() {}

func (x *NodeScore) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScore.ProtoReflect.Descriptor instead.
func (*NodeScore) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *NodeScore) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeScore) GetEta() float64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

func (x *NodeScore) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *NodeScore) GetFinalScore() float64 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type ScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*NodeScore           `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreResponse) GetScores() []*NodeScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type PlacementCommittedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodUid        string                 `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"` // True = successfully bound, False = bind failed / unreserved
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementCommittedRequest) Reset() {
	*x = PlacementCommittedRequest{}
	mi := &file_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementCommittedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementCommittedRequest) ProtoMessage() {}

func (x *PlacementCommittedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementCommittedRequest.ProtoReflect.Descriptor instead.
func (*PlacementCommittedRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *PlacementCommittedRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PlacementCommittedRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PlacementCommittedRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PlacementCommittedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementCommittedResponse) Reset() {
	*x = PlacementCommittedResponse{}
	mi := &file_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementCommittedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementCommittedResponse) ProtoMessage() {}

func (x *PlacementCommittedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementCommittedResponse.ProtoReflect.Descriptor instead.
func (*PlacementCommittedResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *PlacementCommittedResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_sentinel_proto protoreflect.FileDescriptor

const file_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x0esentinel.proto\x12\bsentinel\"\xd2\x01\n" +
	"\aPodSpec\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12.\n" +
	"\x13cpu_cores_requested\x18\x04 \x01(\x01R\x11cpuCoresRequested\x12.\n" +
	"\x13memory_gb_requested\x18\x05 \x01(\x01R\x11memoryGbRequested\x12#\n" +
	"\rworkload_type\x18\x06 \x01(\tR\fworkloadType\"\xcb\x05\n" +
	"\rNodeCandidate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fallocatable_cpu\x18\x02 \x01(\x01R\x0eallocatableCpu\x122\n" +
	"\x15allocatable_memory_gb\x18\x03 \x01(\x01R\x13allocatableMemoryGb\x12=\n" +
	"\x1bscheduler_expected_free_cpu\x18\x04 \x01(\x01R\x18schedulerExpectedFreeCpu\x12H\n" +
	"!scheduler_expected_free_memory_gb\x18\x05 \x01(\x01R\x1dschedulerExpectedFreeMemoryGb\x128\n" +
	"\x18reported_allocatable_cpu\x18\x06 \x01(\x01R\x16reportedAllocatableCpu\x12*\n" +
	"\x11reported_used_cpu\x18\a \x01(\x01R\x0freportedUsedCpu\x12*\n" +
	"\x11reported_free_cpu\x18\b \x01(\x01R\x0freportedFreeCpu\x12C\n" +
	"\x1ereported_allocatable_memory_gb\x18\t \x01(\x01R\x1breportedAllocatableMemoryGb\x125\n" +
	"\x17reported_used_memory_gb\x18\n" +
	" \x01(\x01R\x14reportedUsedMemoryGb\x125\n" +
	"\x17reported_free_memory_gb\x18\v \x01(\x01R\x14reportedFreeMemoryGb\x128\n" +
	"\x18last_heartbeat_timestamp\x18\f \x01(\x01R\x16lastHeartbeatTimestamp\x12<\n" +
	"\x1arecent_heartbeat_intervals\x18\r \x03(\x01R\x18recentHeartbeatIntervals\"x\n" +
	"\fScoreRequest\x12#\n" +
	"\x03pod\x18\x01 \x01(\v2\x11.sentinel.PodSpecR\x03pod\x12-\n" +
	"\x05nodes\x18\x02 \x03(\v2\x17.sentinel.NodeCandidateR\x05nodes\x12\x14\n" +
	"\x05gamma\x18\x03 \x01(\x01R\x05gamma\"w\n" +
	"\tNodeScore\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03eta\x18\x02 \x01(\x01R\x03eta\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1f\n" +
	"\vfinal_score\x18\x04 \x01(\x01R\n" +
	"finalScore\"<\n" +
	"\rScoreResponse\x12+\n" +
	"\x06scores\x18\x01 \x03(\v2\x13.sentinel.NodeScoreR\x06scores\"g\n" +
	"\x19PlacementCommittedRequest\x12\x17\n" +
	"\apod_uid\x18\x01 \x01(\tR\x06podUid\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"@\n" +
	"\x1aPlacementCommittedResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xb8\x01\n" +
	"\x16ACOPredictiveScheduler\x12=\n" +
	"\n" +
	"ScoreNodes\x12\x16.sentinel.ScoreRequest\x1a\x17.sentinel.ScoreResponse\x12_\n" +
	"\x12PlacementCommitted\x12#.sentinel.PlacementCommittedRequest\x1a$.sentinel.PlacementCommittedResponseB\x14Z\x12v2/go_plugin/pb;pbb\x06proto3"

var (
	file_sentinel_proto_rawDescOnce sync.Once
	file_sentinel_proto_rawDescData []byte
)

func file_sentinel_proto_rawDescGZIP() []byte {
	file_sentinel_proto_rawDescOnce.Do(func() {
		file_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_proto_rawDesc), len(file_sentinel_proto_rawDesc)))
	})
	return file_sentinel_proto_rawDescData
}

var file_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sentinel_proto_goTypes = []any{
	(*PodSpec)(nil),                    // 0: sentinel.PodSpec
	(*NodeCandidate)(nil),              // 1: sentinel.NodeCandidate
	(*ScoreRequest)(nil),               // 2: sentinel.ScoreRequest
	(*NodeScore)(nil),                  // 3: sentinel.NodeScore
	(*ScoreResponse)(nil),              // 4: sentinel.ScoreResponse
	(*PlacementCommittedRequest)(nil),  // 5: sentinel.PlacementCommittedRequest
	(*PlacementCommittedResponse)(nil), // 6: sentinel.PlacementCommittedResponse
}
var file_sentinel_proto_depIdxs = []int32{
	0, // 0: sentinel.ScoreRequest.pod:type_name -> sentinel.PodSpec
	1, // 1: sentinel.ScoreRequest.nodes:type_name -> sentinel.NodeCandidate
	3, // 2: sentinel.ScoreResponse.scores:type_name -> sentinel.NodeScore
	2, // 3: sentinel.ACOPredictiveScheduler.ScoreNodes:input_type -> sentinel.ScoreRequest
	5, // 4: sentinel.ACOPredictiveScheduler.PlacementCommitted:input_type -> sentinel.PlacementCommittedRequest
	4, // 5: sentinel.ACOPredictiveScheduler.ScoreNodes:output_type -> sentinel.ScoreResponse
	6, // 6: sentinel.ACOPredictiveScheduler.PlacementCommitted:output_type -> sentinel.PlacementCommittedResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sentinel_proto_init() }
func file_sentinel_proto_init() {
	if File_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_proto_rawDesc), len(file_sentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinel_proto_goTypes,
		DependencyIndexes: file_sentinel_proto_depIdxs,
		MessageInfos:      file_sentinel_proto_msgTypes,
	}.Build()
	File_sentinel_proto = out.File
	file_sentinel_proto_goTypes = nil
	file_sentinel_proto_depIdxs = nil
}
