apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    # Maps telemetry data as expected by the Go plugin
    aco-sentinel.io/node-candidates: '["aco-sentinel-control-plane"]'
spec:
  schedulerName: aco-sentinel-scheduler
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
