# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sentinel_pb2 as sentinel__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentinel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ACOPredictiveSchedulerStub:
    """Service coordinating custom scoring and placement checks between K8s and ACO
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreNodes = channel.unary_unary(
                '/sentinel.ACOPredictiveScheduler/ScoreNodes',
                request_serializer=sentinel__pb2.ScoreRequest.SerializeToString,
                response_deserializer=sentinel__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.PlacementCommitted = channel.unary_unary(
                '/sentinel.ACOPredictiveScheduler/PlacementCommitted',
                request_serializer=sentinel__pb2.PlacementCommittedRequest.SerializeToString,
                response_deserializer=sentinel__pb2.PlacementCommittedResponse.FromString,
                _registered_method=True)


class ACOPredictiveSchedulerServicer:
    """Service coordinating custom scoring and placement checks between K8s and ACO
    """

    def ScoreNodes(self, request, context):
        """Score nodes based on cost engine and predictive trust heuristic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlacementCommitted(self, request, context):
        """Confirms the placement of a pod to commit pheromones or rollback reservations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ACOPredictiveSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreNodes,
                    request_deserializer=sentinel__pb2.ScoreRequest.FromString,
                    response_serializer=sentinel__pb2.ScoreResponse.SerializeToString,
            ),
            'PlacementCommitted': grpc.unary_unary_rpc_method_handler(
                    servicer.PlacementCommitted,
                    request_deserializer=sentinel__pb2.PlacementCommittedRequest.FromString,
                    response_serializer=sentinel__pb2.PlacementCommittedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.ACOPredictiveScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.ACOPredictiveScheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ACOPredictiveScheduler:
    """Service coordinating custom scoring and placement checks between K8s and ACO
    """

    @staticmethod
    def ScoreNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.ACOPredictiveScheduler/ScoreNodes',
            sentinel__pb2.ScoreRequest.SerializeToString,
            sentinel__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlacementCommitted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.ACOPredictiveScheduler/PlacementCommitted',
            sentinel__pb2.PlacementCommittedRequest.SerializeToString,
            sentinel__pb2.PlacementCommittedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
